spinometer = User.create(:name => 'spinometer')
keepitcosmic = User.create(:name => 'keepitcosmic')
screamindetroit= User.create(:name => 'ScreaminDetroit')
trashboat = User.create(:name => '---Trash-Boat---')
ianmalcom = User.create(:name => 'ianmalcom')
halebw = User.create(:name => 'halebw')
franchise1140 = User.create(:name => 'franchise1140')

spinometer.posts.create(:content => 'The more talented the actor, the less likely we are to know what they\'re really like.')
keepitcosmic.posts.create(:content => 'Calves drink their mother cow’s milk until they’re old enough to realize one day they can just eat the floor.')
screamindetroit.posts.create(:content => 'The two main characters of VeggieTales are both fruits.')
trashboat.posts.create(:content => 'Bricks are just domesticated rocks.')
ianmalcom.posts.create(:content => 'Apple spent billions to build a campus to look like the home button they just got rid of.')
halebw.posts.create(:content => 'Cookie Monster never eats any cookies. Instead he breaks them into small pieces and leaves the crumbs on the floor. This is why he is truly a monster.')